#:import menubar menubar
<MenuBar>:
    orientation: 'horizontal'
    padding: 5

    button_exit: button_exit
    button_mirror: button_mirror
    button_lesson: button_lesson

    Button:
        id: button_exit
        text: 'Exit'
        on_press: root.exit()

    Button:
        id: button_mirror
        text: 'Mirror'
        on_press: root.mirror()

    Button:
        id: button_lesson
        text: 'Lesson'
        on_press: root.lesson()
